name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r toptek/requirements-lite.txt
      - name: Lint
        run: |
          ruff check .
          black --check .
          bandit -r toptek -q
      - name: Type check
        run: |
          mypy --config-file mypy.ini toptek tests
      - name: Tests
        env:
          PERF_CHECK: 0
        run: |
          pytest --maxfail=1 --disable-warnings -q
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.os }}-${{ matrix.python-version }}
          path: |
            reports
            models
            data/bank
          if-no-files-found: ignore
